apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque

data:
  # generate base64 hashes: `echo -n "<password>" | base64
  # decode base64: echo "<base64 string>" | base64 --decode 
  username: ZGF0YXNjaWVudGVzdDEyMzQ= # `administrator` in base64
  password: ZGF0YXNjaWVudGVzdDEyMzQ= # `datascientest1234` in base64



