apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels: 
      app: mysql
  serviceName: mysql
  replicas: 3 # desired # of mysql instances: 1 effective and 2 read-only backups
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: mysql-init
          image: mysql:latest
          command:
          - bash
          - "-c"
          - |
            set -ex
            [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
            ordinal=${BASH_REMATCH[1]}
            if [[ $ordinal -eq 0 ]]; then
              printf "I am the primary"
            else
              printf "I am a read-only replica"
            fi
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret  
                  key: username  
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP # gets the pod's IP address dynamically 
          ports:
          - name: mysql
            containerPort: 3306
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "mysqladmin ping -h localhost"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "mysqladmin ping -h localhost"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql # Where MySQL data is stored inside the pod


  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ['ReadWriteOnce'] # Mounted as r-w by a single node
      resources:
        requests:
          storage: 1Gi
            